import 'package:flutter/widgets.dart';

/// Languages intentionally offered in the product. The enum value is persisted,
/// which keeps existing user selections stable when a language is added.
enum AppLanguage {
  english,
  turkish,
  portugueseBrazil,
  spanishLatinAmerica,
  french,
  german,
  swedish,
  norwegian,
}

extension AppLanguageDetails on AppLanguage {
  Locale get locale => switch (this) {
    AppLanguage.english => const Locale('en'),
    AppLanguage.turkish => const Locale('tr'),
    AppLanguage.portugueseBrazil => const Locale('pt', 'BR'),
    AppLanguage.spanishLatinAmerica => const Locale('es', '419'),
    AppLanguage.french => const Locale('fr'),
    AppLanguage.german => const Locale('de'),
    AppLanguage.swedish => const Locale('sv'),
    AppLanguage.norwegian => const Locale('nb'),
  };

  /// Native names make the picker usable even before its own copy changes.
  String get nativeName => switch (this) {
    AppLanguage.english => 'English',
    AppLanguage.turkish => 'Türkçe',
    AppLanguage.portugueseBrazil => 'Português (Brasil)',
    AppLanguage.spanishLatinAmerica => 'Español (Latinoamérica)',
    AppLanguage.french => 'Français',
    AppLanguage.german => 'Deutsch',
    AppLanguage.swedish => 'Svenska',
    AppLanguage.norwegian => 'Norsk bokmål',
  };

  static AppLanguage fromLocale(Locale locale) => switch (locale.languageCode) {
    'tr' => AppLanguage.turkish,
    'pt' => AppLanguage.portugueseBrazil,
    'es' => AppLanguage.spanishLatinAmerica,
    'fr' => AppLanguage.french,
    'de' => AppLanguage.german,
    'sv' => AppLanguage.swedish,
    'nb' || 'no' => AppLanguage.norwegian,
    _ => AppLanguage.english,
  };
}

/// Copy is keyed by stable English source strings while the app migrates to
/// generated ARB files. Each non-English key is explicit and easy to review.
class SoluCopy {
  const SoluCopy._();

  static String? lookup(AppLanguage language, String source) =>
      _catalog[language]?[source];

  static const _catalog = <AppLanguage, Map<String, String>>{
    AppLanguage.portugueseBrazil: _portugueseBrazil,
    AppLanguage.spanishLatinAmerica: _spanishLatinAmerica,
    AppLanguage.french: _french,
    AppLanguage.german: _german,
    AppLanguage.swedish: _swedish,
    AppLanguage.norwegian: _norwegian,
  };
}

extension SoluLocalization on BuildContext {
  AppLanguage get appLanguage =>
      AppLanguageDetails.fromLocale(Localizations.localeOf(this));

  bool get isTurkish => appLanguage == AppLanguage.turkish;

  String l10n(String english, String turkish) {
    if (appLanguage == AppLanguage.turkish) return turkish;
    return SoluCopy.lookup(appLanguage, english) ?? english;
  }

  /// Formats a stable translation key. Dynamic values must not be embedded in
  /// [l10n]'s source-string key, otherwise catalog lookup can never match
  /// them. Templates use `{name}` placeholders.
  String l10nTemplate(
    String key, {
    required String english,
    required String turkish,
    required Map<String, String> values,
  }) {
    var template = appLanguage == AppLanguage.turkish
        ? turkish
        : SoluCopy.lookup(appLanguage, key) ?? english;
    for (final value in values.entries) {
      template = template.replaceAll('{${value.key}}', value.value);
    }
    return template;
  }
}

const _portugueseBrazil = <String, String>{
  'Today': 'Hoje',
  'Forecast': 'Previsão',
  'Locations': 'Locais',
  'Settings': 'Configurações',
  'FISHING CONDITION': 'CONDIÇÃO DE PESCA',
  'ACTIVITY TIMELINE': 'LINHA DO TEMPO DE ATIVIDADE',
  'WEATHER': 'CLIMA',
  'SOLUNAR DATA': 'DADOS SOLUNARES',
  'WHY?': 'POR QUÊ?',
  'SCORE ': 'PONTUAÇÃO ',
  'Major window': 'Janela principal',
  'Minor window': 'Janela secundária',
  'Daylight': 'Luz do dia',
  'MAJOR': 'PRINCIPAL',
  'MINOR': 'SECUNDÁRIO',
  'Hourly Activity': 'Atividade por hora',
  'Solunar Periods': 'Períodos solunares',
  'Hourly Weather': 'Clima por hora',
  'Set Reminder': 'Definir lembrete',
  'Major period': 'Período principal',
  'Minor period': 'Período secundário',
  'Passed': 'Encerrado',
  'TEMP': 'TEMP.',
  'WIND': 'VENTO',
  'PRESSURE': 'PRESSÃO',
  'ILLUM': 'ILUM.',
  'offline': 'off-line',
  'NEXT 7 DAYS': 'PRÓXIMOS 7 DIAS',
  'Tomorrow': 'Amanhã',
  '14-day forecasts': 'Previsões de 14 dias',
  'My Locations': 'Meus locais',
  'ACTIVE': 'ATIVO',
  'DETAILS': 'DETALHES',
  'Multiple locations': 'Vários locais',
  'Add location': 'Adicionar local',
  'Switch location': 'Trocar local',
  'Add a location': 'Adicionar um local',
  'Use my current location': 'Usar minha localização atual',
  'Search a city…': 'Pesquisar uma cidade…',
  'SUGGESTIONS': 'SUGESTÕES',
  'No matches.': 'Nenhum resultado.',
  'Not now': 'Agora não',
  'Open settings': 'Abrir configurações',
  'Updating weather…': 'Atualizando o clima…',
  'Weather unavailable': 'Dados meteorológicos indisponíveis',
  'UNITS & FORMAT': 'UNIDADES E FORMATO',
  'Units': 'Unidades',
  'Time format': 'Formato de hora',
  'Example': 'Exemplo',
  'NOTIFICATIONS': 'NOTIFICAÇÕES',
  'Daily summary': 'Resumo diário',
  'High-score day alert': 'Alerta de dia com alta pontuação',
  'Period reminders': 'Lembretes de períodos',
  'APPEARANCE & LANGUAGE': 'APARÊNCIA E IDIOMA',
  'Theme': 'Tema',
  'Language': 'Idioma',
  'System': 'Sistema',
  'Dark': 'Escuro',
  'Light': 'Claro',
  'Privacy policy': 'Política de privacidade',
  'About AnglerPulse': 'Sobre o AnglerPulse',
  'How is the score calculated?': 'Como a pontuação é calculada?',
  'Moon phase': 'Fase da lua',
  'Dawn / dusk overlap': 'Sobreposição de amanhecer e anoitecer',
  'Pressure trend': 'Tendência da pressão',
  'Season': 'Estação',
  'Smart trip alert': 'Alerta inteligente de pesca',
  'Smart trip alerts': 'Alertas inteligentes de pesca',
  'ALERT RULE': 'REGRA DE ALERTA',
  'Minimum day score': 'Pontuação mínima do dia',
  'Notify before the major window': 'Notificar antes da janela principal',
  'PLANNED FISHING TIME': 'HORÁRIO DE PESCA PLANEJADO',
  'When do you plan to fish?': 'Quando você pretende pescar?',
  'Copy trip brief': 'Copiar resumo da viagem',
  'Trip brief copied.': 'Resumo da viagem copiado.',
  'LIVE': 'AO VIVO',
  'smart_alert_summary':
      '{score}/5+ dias · {lead} min antes de uma janela principal.',
  'weather_minutes_ago': 'há {value} min',
  'weather_hours_ago': 'há {value} h',
  'spot_compare_best_window':
      'Melhor janela principal perto do seu plano: {window}',
  'spot_compare_major_window': 'Principal {window}',
  'WHEN TO GO': 'QUANDO IR',
  'Best fishing windows': 'Melhores janelas de pesca',
  'Next 7 days · active spot': 'Próximos 7 dias · local ativo',
  'Next 14 days · all spots': 'Próximos 14 dias · todos os locais',
  'See 14 days and all spots with Pro':
      'Veja 14 dias e todos os locais com o Pro',
  'Best windows across 14 days and all spots':
      'Melhores janelas em 14 dias e todos os locais',
  'Ranked by the on-device astronomy model; live weather is not part of future-day rankings.':
      'Classificado pelo modelo astronômico no dispositivo; o clima ao vivo não entra nos dias futuros.',
  'You are offline, but the solunar times below are computed on this device and remain accurate. Weather refreshes when you reconnect.':
      'Você está offline, mas os horários solunares abaixo são calculados neste dispositivo e continuam válidos. O clima é atualizado quando você reconectar.',
};

const _spanishLatinAmerica = <String, String>{
  'Today': 'Hoy',
  'Forecast': 'Pronóstico',
  'Locations': 'Ubicaciones',
  'Settings': 'Configuración',
  'FISHING CONDITION': 'CONDICIÓN DE PESCA',
  'ACTIVITY TIMELINE': 'LÍNEA DE ACTIVIDAD',
  'WEATHER': 'CLIMA',
  'SOLUNAR DATA': 'DATOS SOLUNARES',
  'WHY?': '¿POR QUÉ?',
  'SCORE ': 'PUNTAJE ',
  'Major window': 'Ventana principal',
  'Minor window': 'Ventana secundaria',
  'Daylight': 'Luz diurna',
  'MAJOR': 'PRINCIPAL',
  'MINOR': 'SECUNDARIO',
  'Hourly Activity': 'Actividad por hora',
  'Solunar Periods': 'Períodos solunares',
  'Hourly Weather': 'Clima por hora',
  'Set Reminder': 'Configurar recordatorio',
  'Major period': 'Período principal',
  'Minor period': 'Período secundario',
  'Passed': 'Finalizado',
  'TEMP': 'TEMP.',
  'WIND': 'VIENTO',
  'PRESSURE': 'PRESIÓN',
  'ILLUM': 'ILUM.',
  'offline': 'sin conexión',
  'NEXT 7 DAYS': 'PRÓXIMOS 7 DÍAS',
  'Tomorrow': 'Mañana',
  '14-day forecasts': 'Pronósticos de 14 días',
  'My Locations': 'Mis ubicaciones',
  'ACTIVE': 'ACTIVA',
  'DETAILS': 'DETALLES',
  'Multiple locations': 'Varias ubicaciones',
  'Add location': 'Agregar ubicación',
  'Switch location': 'Cambiar ubicación',
  'Add a location': 'Agregar una ubicación',
  'Use my current location': 'Usar mi ubicación actual',
  'Search a city…': 'Buscar una ciudad…',
  'SUGGESTIONS': 'SUGERENCIAS',
  'No matches.': 'Sin resultados.',
  'Not now': 'Ahora no',
  'Open settings': 'Abrir configuración',
  'Updating weather…': 'Actualizando el clima…',
  'Weather unavailable': 'Datos del clima no disponibles',
  'UNITS & FORMAT': 'UNIDADES Y FORMATO',
  'Units': 'Unidades',
  'Time format': 'Formato de hora',
  'Example': 'Ejemplo',
  'NOTIFICATIONS': 'NOTIFICACIONES',
  'Daily summary': 'Resumen diario',
  'High-score day alert': 'Alerta de día con puntaje alto',
  'Period reminders': 'Recordatorios de períodos',
  'APPEARANCE & LANGUAGE': 'APARIENCIA E IDIOMA',
  'Theme': 'Tema',
  'Language': 'Idioma',
  'System': 'Sistema',
  'Dark': 'Oscuro',
  'Light': 'Claro',
  'Privacy policy': 'Política de privacidad',
  'About AnglerPulse': 'Acerca de AnglerPulse',
  'How is the score calculated?': '¿Cómo se calcula el puntaje?',
  'Moon phase': 'Fase lunar',
  'Dawn / dusk overlap': 'Coincidencia de amanecer y anochecer',
  'Pressure trend': 'Tendencia de presión',
  'Season': 'Temporada',
  'Smart trip alert': 'Alerta inteligente de pesca',
  'Smart trip alerts': 'Alertas inteligentes de pesca',
  'ALERT RULE': 'REGLA DE ALERTA',
  'Minimum day score': 'Puntuación mínima del día',
  'Notify before the major window': 'Avisar antes de la ventana principal',
  'PLANNED FISHING TIME': 'HORA DE PESCA PREVISTA',
  'When do you plan to fish?': '¿Cuándo planeas pescar?',
  'Copy trip brief': 'Copiar resumen de la salida',
  'Trip brief copied.': 'Resumen de la salida copiado.',
  'LIVE': 'EN VIVO',
  'smart_alert_summary':
      'días de {score}/5+ · {lead} min antes de una ventana principal.',
  'weather_minutes_ago': 'hace {value} min',
  'weather_hours_ago': 'hace {value} h',
  'spot_compare_best_window':
      'Mejor ventana principal cerca de tu plan: {window}',
  'spot_compare_major_window': 'Principal {window}',
  'WHEN TO GO': 'CUÁNDO IR',
  'Best fishing windows': 'Mejores ventanas de pesca',
  'Next 7 days · active spot': 'Próximos 7 días · lugar activo',
  'Next 14 days · all spots': 'Próximos 14 días · todos los lugares',
  'See 14 days and all spots with Pro':
      'Ve 14 días y todos los lugares con Pro',
  'Best windows across 14 days and all spots':
      'Mejores ventanas en 14 días y todos los lugares',
  'Ranked by the on-device astronomy model; live weather is not part of future-day rankings.':
      'Clasificado por el modelo astronómico del dispositivo; el clima en vivo no forma parte de los días futuros.',
  'You are offline, but the solunar times below are computed on this device and remain accurate. Weather refreshes when you reconnect.':
      'Estás sin conexión, pero los horarios solunares de abajo se calculan en este dispositivo y siguen siendo válidos. El clima se actualiza cuando vuelvas a conectarte.',
};

const _french = <String, String>{
  'Today': 'Aujourd’hui',
  'Forecast': 'Prévisions',
  'Locations': 'Lieux',
  'Settings': 'Réglages',
  'FISHING CONDITION': 'CONDITIONS DE PÊCHE',
  'ACTIVITY TIMELINE': 'CHRONOLOGIE D’ACTIVITÉ',
  'WEATHER': 'MÉTÉO',
  'SOLUNAR DATA': 'DONNÉES SOLUNAIRES',
  'WHY?': 'POURQUOI ?',
  'SCORE ': 'SCORE ',
  'Major window': 'Créneau majeur',
  'Minor window': 'Créneau mineur',
  'Daylight': 'Lumière du jour',
  'MAJOR': 'MAJEUR',
  'MINOR': 'MINEUR',
  'Hourly Activity': 'Activité horaire',
  'Solunar Periods': 'Périodes solunaires',
  'Hourly Weather': 'Météo horaire',
  'Set Reminder': 'Créer un rappel',
  'Major period': 'Période majeure',
  'Minor period': 'Période mineure',
  'Passed': 'Terminée',
  'TEMP': 'TEMP.',
  'WIND': 'VENT',
  'PRESSURE': 'PRESSION',
  'ILLUM': 'LUMIN.',
  'offline': 'hors ligne',
  'NEXT 7 DAYS': '7 PROCHAINS JOURS',
  'Tomorrow': 'Demain',
  '14-day forecasts': 'Prévisions sur 14 jours',
  'My Locations': 'Mes lieux',
  'ACTIVE': 'ACTIF',
  'DETAILS': 'DÉTAILS',
  'Multiple locations': 'Plusieurs lieux',
  'Add location': 'Ajouter un lieu',
  'Switch location': 'Changer de lieu',
  'Add a location': 'Ajouter un lieu',
  'Use my current location': 'Utiliser ma position actuelle',
  'Search a city…': 'Rechercher une ville…',
  'SUGGESTIONS': 'SUGGESTIONS',
  'No matches.': 'Aucun résultat.',
  'Not now': 'Pas maintenant',
  'Open settings': 'Ouvrir les réglages',
  'Updating weather…': 'Mise à jour de la météo…',
  'Weather unavailable': 'Données météo indisponibles',
  'UNITS & FORMAT': 'UNITÉS ET FORMAT',
  'Units': 'Unités',
  'Time format': 'Format de l’heure',
  'Example': 'Exemple',
  'NOTIFICATIONS': 'NOTIFICATIONS',
  'Daily summary': 'Résumé quotidien',
  'High-score day alert': 'Alerte de journée à score élevé',
  'Period reminders': 'Rappels de périodes',
  'APPEARANCE & LANGUAGE': 'APPARENCE ET LANGUE',
  'Theme': 'Thème',
  'Language': 'Langue',
  'System': 'Système',
  'Dark': 'Sombre',
  'Light': 'Clair',
  'Privacy policy': 'Politique de confidentialité',
  'About AnglerPulse': 'À propos d’AnglerPulse',
  'How is the score calculated?': 'Comment le score est-il calculé ?',
  'Moon phase': 'Phase lunaire',
  'Dawn / dusk overlap': 'Chevauchement entre aube et crépuscule',
  'Pressure trend': 'Tendance de la pression',
  'Season': 'Saison',
  'Smart trip alert': 'Alerte de sortie intelligente',
  'Smart trip alerts': 'Alertes de sortie intelligentes',
  'ALERT RULE': 'RÈGLE D’ALERTE',
  'Minimum day score': 'Score minimal de la journée',
  'Notify before the major window': 'Notifier avant la fenêtre majeure',
  'PLANNED FISHING TIME': 'HEURE DE PÊCHE PRÉVUE',
  'When do you plan to fish?': 'Quand prévoyez-vous de pêcher ?',
  'Copy trip brief': 'Copier le résumé de sortie',
  'Trip brief copied.': 'Résumé de sortie copié.',
  'LIVE': 'EN DIRECT',
  'smart_alert_summary':
      'journées à {score}/5+ · {lead} min avant une fenêtre majeure.',
  'weather_minutes_ago': 'il y a {value} min',
  'weather_hours_ago': 'il y a {value} h',
  'spot_compare_best_window':
      'Meilleure fenêtre majeure près de votre créneau : {window}',
  'spot_compare_major_window': 'Majeure {window}',
  'WHEN TO GO': 'QUAND PARTIR',
  'Best fishing windows': 'Meilleures fenêtres de pêche',
  'Next 7 days · active spot': '7 prochains jours · spot actif',
  'Next 14 days · all spots': '14 prochains jours · tous les spots',
  'See 14 days and all spots with Pro':
      'Voir 14 jours et tous les spots avec Pro',
  'Best windows across 14 days and all spots':
      'Meilleures fenêtres sur 14 jours et tous les spots',
  'Ranked by the on-device astronomy model; live weather is not part of future-day rankings.':
      'Classement selon le modèle astronomique de l’appareil ; la météo en direct n’entre pas dans les jours futurs.',
  'You are offline, but the solunar times below are computed on this device and remain accurate. Weather refreshes when you reconnect.':
      'Vous êtes hors ligne, mais les horaires solunaires ci-dessous sont calculés sur cet appareil et restent exacts. La météo se met à jour dès la reconnexion.',
};

const _german = <String, String>{
  'Today': 'Heute',
  'Forecast': 'Vorhersage',
  'Locations': 'Orte',
  'Settings': 'Einstellungen',
  'FISHING CONDITION': 'ANGELBEDINGUNGEN',
  'ACTIVITY TIMELINE': 'AKTIVITÄTSZEITLEISTE',
  'WEATHER': 'WETTER',
  'SOLUNAR DATA': 'SOLUNARDATEN',
  'WHY?': 'WARUM?',
  'SCORE ': 'WERTUNG ',
  'Major window': 'Hauptfenster',
  'Minor window': 'Nebenfenster',
  'Daylight': 'Tageslicht',
  'MAJOR': 'HAUPT',
  'MINOR': 'NEBEN',
  'Hourly Activity': 'Stündliche Aktivität',
  'Solunar Periods': 'Solunarperioden',
  'Hourly Weather': 'Stündliches Wetter',
  'Set Reminder': 'Erinnerung setzen',
  'Major period': 'Hauptperiode',
  'Minor period': 'Nebenperiode',
  'Passed': 'Vorbei',
  'TEMP': 'TEMP.',
  'WIND': 'WIND',
  'PRESSURE': 'DRUCK',
  'ILLUM': 'BELEUCHT.',
  'offline': 'offline',
  'NEXT 7 DAYS': 'NÄCHSTE 7 TAGE',
  'Tomorrow': 'Morgen',
  '14-day forecasts': '14-Tage-Vorhersagen',
  'My Locations': 'Meine Orte',
  'ACTIVE': 'AKTIV',
  'DETAILS': 'DETAILS',
  'Multiple locations': 'Mehrere Orte',
  'Add location': 'Ort hinzufügen',
  'Switch location': 'Ort wechseln',
  'Add a location': 'Ort hinzufügen',
  'Use my current location': 'Meinen aktuellen Standort verwenden',
  'Search a city…': 'Stadt suchen…',
  'SUGGESTIONS': 'VORSCHLÄGE',
  'No matches.': 'Keine Treffer.',
  'Not now': 'Nicht jetzt',
  'Open settings': 'Einstellungen öffnen',
  'Updating weather…': 'Wetter wird aktualisiert…',
  'Weather unavailable': 'Wetterdaten nicht verfügbar',
  'UNITS & FORMAT': 'EINHEITEN UND FORMAT',
  'Units': 'Einheiten',
  'Time format': 'Zeitformat',
  'Example': 'Beispiel',
  'NOTIFICATIONS': 'BENACHRICHTIGUNGEN',
  'Daily summary': 'Tagesübersicht',
  'High-score day alert': 'Hinweis für Tage mit hoher Wertung',
  'Period reminders': 'Periodenerinnerungen',
  'APPEARANCE & LANGUAGE': 'DARSTELLUNG UND SPRACHE',
  'Theme': 'Design',
  'Language': 'Sprache',
  'System': 'System',
  'Dark': 'Dunkel',
  'Light': 'Hell',
  'Privacy policy': 'Datenschutzerklärung',
  'About AnglerPulse': 'Über AnglerPulse',
  'How is the score calculated?': 'Wie wird die Wertung berechnet?',
  'Moon phase': 'Mondphase',
  'Dawn / dusk overlap': 'Überlappung von Morgen- und Abenddämmerung',
  'Pressure trend': 'Luftdrucktrend',
  'Season': 'Jahreszeit',
  'Smart trip alert': 'Intelligente Angelausflug-Warnung',
  'Smart trip alerts': 'Intelligente Angelausflug-Warnungen',
  'ALERT RULE': 'WARNREGEL',
  'Minimum day score': 'Mindest-Tageswertung',
  'Notify before the major window': 'Vor dem Hauptfenster benachrichtigen',
  'PLANNED FISHING TIME': 'GEPLANTE ANGELZEIT',
  'When do you plan to fish?': 'Wann möchten Sie angeln?',
  'Copy trip brief': 'Ausflugsübersicht kopieren',
  'Trip brief copied.': 'Ausflugsübersicht kopiert.',
  'LIVE': 'LIVE',
  'smart_alert_summary':
      '{score}/5+-Tage · {lead} Min. vor einem Hauptfenster.',
  'weather_minutes_ago': 'vor {value} Min.',
  'weather_hours_ago': 'vor {value} Std.',
  'spot_compare_best_window':
      'Bestes Hauptfenster nahe Ihrer Planung: {window}',
  'spot_compare_major_window': 'Hauptfenster {window}',
  'WHEN TO GO': 'WANN LOSGEHEN',
  'Best fishing windows': 'Beste Angelfenster',
  'Next 7 days · active spot': 'Nächste 7 Tage · aktiver Spot',
  'Next 14 days · all spots': 'Nächste 14 Tage · alle Spots',
  'See 14 days and all spots with Pro':
      'Mit Pro 14 Tage und alle Spots sehen',
  'Best windows across 14 days and all spots':
      'Beste Fenster über 14 Tage und alle Spots',
  'Ranked by the on-device astronomy model; live weather is not part of future-day rankings.':
      'Sortiert nach dem Astronomiemodell auf dem Gerät; Live-Wetter fließt bei künftigen Tagen nicht ein.',
  'You are offline, but the solunar times below are computed on this device and remain accurate. Weather refreshes when you reconnect.':
      'Du bist offline, aber die Solunarzeiten unten werden auf diesem Gerät berechnet und bleiben korrekt. Das Wetter aktualisiert sich, sobald du wieder online bist.',
};

const _swedish = <String, String>{
  'Today': 'I dag',
  'Forecast': 'Prognos',
  'Locations': 'Platser',
  'Settings': 'Inställningar',
  'FISHING CONDITION': 'FISKEFÖRHÅLLANDEN',
  'ACTIVITY TIMELINE': 'AKTIVITETSTIDSLINJE',
  'WEATHER': 'VÄDER',
  'SOLUNAR DATA': 'SOLUNARDATA',
  'WHY?': 'VARFÖR?',
  'SCORE ': 'POÄNG ',
  'Major window': 'Huvudfönster',
  'Minor window': 'Mindre fönster',
  'Daylight': 'Dagsljus',
  'MAJOR': 'HUVUD',
  'MINOR': 'MINDRE',
  'Hourly Activity': 'Aktivitet per timme',
  'Solunar Periods': 'Solunarperioder',
  'Hourly Weather': 'Väder per timme',
  'Set Reminder': 'Ställ in påminnelse',
  'Major period': 'Huvudperiod',
  'Minor period': 'Mindre period',
  'Passed': 'Passerad',
  'TEMP': 'TEMP.',
  'WIND': 'VIND',
  'PRESSURE': 'LUFTTRYCK',
  'ILLUM': 'BELYSN.',
  'offline': 'offline',
  'NEXT 7 DAYS': 'KOMMANDE 7 DAGAR',
  'Tomorrow': 'I morgon',
  '14-day forecasts': '14-dagarsprognoser',
  'My Locations': 'Mina platser',
  'ACTIVE': 'AKTIV',
  'DETAILS': 'DETALJER',
  'Multiple locations': 'Flera platser',
  'Add location': 'Lägg till plats',
  'Switch location': 'Byt plats',
  'Add a location': 'Lägg till en plats',
  'Use my current location': 'Använd min nuvarande plats',
  'Search a city…': 'Sök efter en stad…',
  'SUGGESTIONS': 'FÖRSLAG',
  'No matches.': 'Inga träffar.',
  'Not now': 'Inte nu',
  'Open settings': 'Öppna inställningar',
  'Updating weather…': 'Uppdaterar väder…',
  'Weather unavailable': 'Väderdata är inte tillgängliga',
  'UNITS & FORMAT': 'ENHETER OCH FORMAT',
  'Units': 'Enheter',
  'Time format': 'Tidsformat',
  'Example': 'Exempel',
  'NOTIFICATIONS': 'NOTISER',
  'Daily summary': 'Daglig sammanfattning',
  'High-score day alert': 'Varning för dag med hög poäng',
  'Period reminders': 'Periodpåminnelser',
  'APPEARANCE & LANGUAGE': 'UTSEENDE OCH SPRÅK',
  'Theme': 'Tema',
  'Language': 'Språk',
  'System': 'System',
  'Dark': 'Mörkt',
  'Light': 'Ljust',
  'Privacy policy': 'Integritetspolicy',
  'About AnglerPulse': 'Om AnglerPulse',
  'How is the score calculated?': 'Hur beräknas poängen?',
  'Moon phase': 'Månfas',
  'Dawn / dusk overlap': 'Överlappning mellan gryning och skymning',
  'Pressure trend': 'Lufttryckstrend',
  'Season': 'Säsong',
  'Smart trip alert': 'Smart fiskelarm',
  'Smart trip alerts': 'Smarta fiskelarm',
  'ALERT RULE': 'LARMREGEL',
  'Minimum day score': 'Lägsta dagsbetyg',
  'Notify before the major window': 'Meddela före huvudfönstret',
  'PLANNED FISHING TIME': 'PLANERAD FISKETID',
  'When do you plan to fish?': 'När planerar du att fiska?',
  'Copy trip brief': 'Kopiera turöversikt',
  'Trip brief copied.': 'Turöversikt kopierad.',
  'LIVE': 'LIVE',
  'smart_alert_summary':
      'dagar med {score}/5+ · {lead} min före ett huvudfönster.',
  'weather_minutes_ago': 'för {value} min sedan',
  'weather_hours_ago': 'för {value} h sedan',
  'spot_compare_best_window': 'Bästa huvudfönstret nära din plan: {window}',
  'spot_compare_major_window': 'Huvudfönster {window}',
  'WHEN TO GO': 'NÄR DU BÖR ÅKA',
  'Best fishing windows': 'Bästa fiskefönstren',
  'Next 7 days · active spot': 'Kommande 7 dagar · aktiv plats',
  'Next 14 days · all spots': 'Kommande 14 dagar · alla platser',
  'See 14 days and all spots with Pro':
      'Se 14 dagar och alla platser med Pro',
  'Best windows across 14 days and all spots':
      'Bästa fönstren över 14 dagar och alla platser',
  'Ranked by the on-device astronomy model; live weather is not part of future-day rankings.':
      'Rankas av astronomimodellen på enheten; liveväder ingår inte för framtida dagar.',
  'You are offline, but the solunar times below are computed on this device and remain accurate. Weather refreshes when you reconnect.':
      'Du är offline, men solunartiderna nedan beräknas på den här enheten och är fortfarande korrekta. Vädret uppdateras när du är ansluten igen.',
};

const _norwegian = <String, String>{
  'Today': 'I dag',
  'Forecast': 'Varsel',
  'Locations': 'Steder',
  'Settings': 'Innstillinger',
  'FISHING CONDITION': 'FISKEFORHOLD',
  'ACTIVITY TIMELINE': 'AKTIVITETSTIDSLINJE',
  'WEATHER': 'VÆR',
  'SOLUNAR DATA': 'SOLUNARDATA',
  'WHY?': 'HVORFOR?',
  'SCORE ': 'POENG ',
  'Major window': 'Hovedvindu',
  'Minor window': 'Mindre vindu',
  'Daylight': 'Dagslys',
  'MAJOR': 'HOVED',
  'MINOR': 'MINDRE',
  'Hourly Activity': 'Aktivitet per time',
  'Solunar Periods': 'Solunarperioder',
  'Hourly Weather': 'Vær per time',
  'Set Reminder': 'Sett påminnelse',
  'Major period': 'Hovedperiode',
  'Minor period': 'Mindre periode',
  'Passed': 'Passert',
  'TEMP': 'TEMP.',
  'WIND': 'VIND',
  'PRESSURE': 'TRYKK',
  'ILLUM': 'BELYSN.',
  'offline': 'frakoblet',
  'NEXT 7 DAYS': 'NESTE 7 DAGER',
  'Tomorrow': 'I morgen',
  '14-day forecasts': '14-dagersvarsler',
  'My Locations': 'Mine steder',
  'ACTIVE': 'AKTIV',
  'DETAILS': 'DETALJER',
  'Multiple locations': 'Flere steder',
  'Add location': 'Legg til sted',
  'Switch location': 'Bytt sted',
  'Add a location': 'Legg til et sted',
  'Use my current location': 'Bruk min nåværende posisjon',
  'Search a city…': 'Søk etter en by…',
  'SUGGESTIONS': 'FORSLAG',
  'No matches.': 'Ingen treff.',
  'Not now': 'Ikke nå',
  'Open settings': 'Åpne innstillinger',
  'Updating weather…': 'Oppdaterer vær…',
  'Weather unavailable': 'Værdata er ikke tilgjengelige',
  'UNITS & FORMAT': 'ENHETER OG FORMAT',
  'Units': 'Enheter',
  'Time format': 'Tidsformat',
  'Example': 'Eksempel',
  'NOTIFICATIONS': 'VARSLER',
  'Daily summary': 'Daglig oppsummering',
  'High-score day alert': 'Varsel om dag med høy poengsum',
  'Period reminders': 'Periodepåminnelser',
  'APPEARANCE & LANGUAGE': 'UTSEENDE OG SPRÅK',
  'Theme': 'Tema',
  'Language': 'Språk',
  'System': 'System',
  'Dark': 'Mørk',
  'Light': 'Lys',
  'Privacy policy': 'Personvernerklæring',
  'About AnglerPulse': 'Om AnglerPulse',
  'How is the score calculated?': 'Hvordan beregnes poengsummen?',
  'Moon phase': 'Månefase',
  'Dawn / dusk overlap': 'Overlapp mellom daggry og skumring',
  'Pressure trend': 'Trykktrend',
  'Season': 'Årstid',
  'Smart trip alert': 'Smart fiskevarsel',
  'Smart trip alerts': 'Smarte fiskevarsler',
  'ALERT RULE': 'VARSELREGEL',
  'Minimum day score': 'Laveste dagsresultat',
  'Notify before the major window': 'Varsle før hovedvinduet',
  'PLANNED FISHING TIME': 'PLANLAGT FISKETID',
  'When do you plan to fish?': 'Når planlegger du å fiske?',
  'Copy trip brief': 'Kopier turoversikt',
  'Trip brief copied.': 'Turoversikt kopiert.',
  'LIVE': 'LIVE',
  'smart_alert_summary': 'dager med {score}/5+ · {lead} min før et hovedvindu.',
  'weather_minutes_ago': 'for {value} min siden',
  'weather_hours_ago': 'for {value} t siden',
  'spot_compare_best_window': 'Beste hovedvindu nær planen din: {window}',
  'spot_compare_major_window': 'Hovedvindu {window}',
  'WHEN TO GO': 'NÅR DU BØR DRA',
  'Best fishing windows': 'Beste fiskevinduer',
  'Next 7 days · active spot': 'Neste 7 dager · aktivt sted',
  'Next 14 days · all spots': 'Neste 14 dager · alle steder',
  'See 14 days and all spots with Pro':
      'Se 14 dager og alle steder med Pro',
  'Best windows across 14 days and all spots':
      'Beste vinduer over 14 dager og alle steder',
  'Ranked by the on-device astronomy model; live weather is not part of future-day rankings.':
      'Rangert av astronomimodellen på enheten; livevær inngår ikke for fremtidige dager.',
  'You are offline, but the solunar times below are computed on this device and remain accurate. Weather refreshes when you reconnect.':
      'Du er frakoblet, men solunartidene nedenfor beregnes på denne enheten og er fortsatt korrekte. Været oppdateres når du kobler til igjen.',
};
