import 'package:flutter/widgets.dart';

/// Languages intentionally offered in the product. The enum value is persisted,
/// which keeps existing user selections stable when a language is added.
enum AppLanguage {
  english,
  turkish,
  portugueseBrazil,
  spanishLatinAmerica,
  french,
  german,
  swedish,
  norwegian,
}

extension AppLanguageDetails on AppLanguage {
  Locale get locale => switch (this) {
    AppLanguage.english => const Locale('en'),
    AppLanguage.turkish => const Locale('tr'),
    AppLanguage.portugueseBrazil => const Locale('pt', 'BR'),
    AppLanguage.spanishLatinAmerica => const Locale('es', '419'),
    AppLanguage.french => const Locale('fr'),
    AppLanguage.german => const Locale('de'),
    AppLanguage.swedish => const Locale('sv'),
    AppLanguage.norwegian => const Locale('nb'),
  };

  /// Native names make the picker usable even before its own copy changes.
  String get nativeName => switch (this) {
    AppLanguage.english => 'English',
    AppLanguage.turkish => 'Türkçe',
    AppLanguage.portugueseBrazil => 'Português (Brasil)',
    AppLanguage.spanishLatinAmerica => 'Español (Latinoamérica)',
    AppLanguage.french => 'Français',
    AppLanguage.german => 'Deutsch',
    AppLanguage.swedish => 'Svenska',
    AppLanguage.norwegian => 'Norsk bokmål',
  };

  static AppLanguage fromLocale(Locale locale) => switch (locale.languageCode) {
    'tr' => AppLanguage.turkish,
    'pt' => AppLanguage.portugueseBrazil,
    'es' => AppLanguage.spanishLatinAmerica,
    'fr' => AppLanguage.french,
    'de' => AppLanguage.german,
    'sv' => AppLanguage.swedish,
    'nb' || 'no' => AppLanguage.norwegian,
    _ => AppLanguage.english,
  };
}

/// Copy is keyed by stable English source strings while the app migrates to
/// generated ARB files. Each non-English key is explicit and easy to review.
class SoluCopy {
  const SoluCopy._();

  static String? lookup(AppLanguage language, String source) =>
      _catalog[language]?[source];

  static const _catalog = <AppLanguage, Map<String, String>>{
    AppLanguage.portugueseBrazil: _portugueseBrazil,
    AppLanguage.spanishLatinAmerica: _spanishLatinAmerica,
    AppLanguage.french: _french,
    AppLanguage.german: _german,
    AppLanguage.swedish: _swedish,
    AppLanguage.norwegian: _norwegian,
  };
}

extension SoluLocalization on BuildContext {
  AppLanguage get appLanguage =>
      AppLanguageDetails.fromLocale(Localizations.localeOf(this));

  bool get isTurkish => appLanguage == AppLanguage.turkish;

  String l10n(String english, String turkish) {
    if (appLanguage == AppLanguage.turkish) return turkish;
    return SoluCopy.lookup(appLanguage, english) ?? english;
  }
}

const _portugueseBrazil = <String, String>{
  'Today': 'Hoje',
  'Forecast': 'Previsão',
  'Locations': 'Locais',
  'Settings': 'Configurações',
  'FISHING CONDITION': 'CONDIÇÃO DE PESCA',
  'ACTIVITY TIMELINE': 'LINHA DO TEMPO DE ATIVIDADE',
  'WEATHER': 'CLIMA',
  'SOLUNAR DATA': 'DADOS SOLUNARES',
  'WHY?': 'POR QUÊ?',
  'SCORE ': 'PONTUAÇÃO ',
  'Major window': 'Janela principal',
  'Minor window': 'Janela secundária',
  'Daylight': 'Luz do dia',
  'MAJOR': 'PRINCIPAL',
  'MINOR': 'SECUNDÁRIO',
  'Hourly Activity': 'Atividade por hora',
  'Solunar Periods': 'Períodos solunares',
  'Hourly Weather': 'Clima por hora',
  'Set Reminder': 'Definir lembrete',
  'Major period': 'Período principal',
  'Minor period': 'Período secundário',
  'Passed': 'Encerrado',
  'TEMP': 'TEMP.',
  'WIND': 'VENTO',
  'PRESSURE': 'PRESSÃO',
  'ILLUM': 'ILUM.',
  'offline': 'off-line',
  'NEXT 7 DAYS': 'PRÓXIMOS 7 DIAS',
  'Tomorrow': 'Amanhã',
  '14-day forecasts': 'Previsões de 14 dias',
  'My Locations': 'Meus locais',
  'ACTIVE': 'ATIVO',
  'DETAILS': 'DETALHES',
  'Multiple locations': 'Vários locais',
  'Add location': 'Adicionar local',
  'Switch location': 'Trocar local',
  'Add a location': 'Adicionar um local',
  'Use my current location': 'Usar minha localização atual',
  'Search a city…': 'Pesquisar uma cidade…',
  'SUGGESTIONS': 'SUGESTÕES',
  'No matches.': 'Nenhum resultado.',
  'Not now': 'Agora não',
  'Open settings': 'Abrir configurações',
  'Updating weather…': 'Atualizando o clima…',
  'Weather unavailable': 'Dados meteorológicos indisponíveis',
  'UNITS & FORMAT': 'UNIDADES E FORMATO',
  'Units': 'Unidades',
  'Time format': 'Formato de hora',
  'Example': 'Exemplo',
  'NOTIFICATIONS': 'NOTIFICAÇÕES',
  'Daily summary': 'Resumo diário',
  'High-score day alert': 'Alerta de dia com alta pontuação',
  'Period reminders': 'Lembretes de períodos',
  'APPEARANCE & LANGUAGE': 'APARÊNCIA E IDIOMA',
  'Theme': 'Tema',
  'Language': 'Idioma',
  'System': 'Sistema',
  'Dark': 'Escuro',
  'Light': 'Claro',
  'Privacy policy': 'Política de privacidade',
  'About AnglerPulse': 'Sobre o AnglerPulse',
  'How is the score calculated?': 'Como a pontuação é calculada?',
  'Moon phase': 'Fase da lua',
  'Dawn / dusk overlap': 'Sobreposição de amanhecer e anoitecer',
  'Pressure trend': 'Tendência da pressão',
  'Season': 'Estação',
};

const _spanishLatinAmerica = <String, String>{
  'Today': 'Hoy',
  'Forecast': 'Pronóstico',
  'Locations': 'Ubicaciones',
  'Settings': 'Configuración',
  'FISHING CONDITION': 'CONDICIÓN DE PESCA',
  'ACTIVITY TIMELINE': 'LÍNEA DE ACTIVIDAD',
  'WEATHER': 'CLIMA',
  'SOLUNAR DATA': 'DATOS SOLUNARES',
  'WHY?': '¿POR QUÉ?',
  'SCORE ': 'PUNTAJE ',
  'Major window': 'Ventana principal',
  'Minor window': 'Ventana secundaria',
  'Daylight': 'Luz diurna',
  'MAJOR': 'PRINCIPAL',
  'MINOR': 'SECUNDARIO',
  'Hourly Activity': 'Actividad por hora',
  'Solunar Periods': 'Períodos solunares',
  'Hourly Weather': 'Clima por hora',
  'Set Reminder': 'Configurar recordatorio',
  'Major period': 'Período principal',
  'Minor period': 'Período secundario',
  'Passed': 'Finalizado',
  'TEMP': 'TEMP.',
  'WIND': 'VIENTO',
  'PRESSURE': 'PRESIÓN',
  'ILLUM': 'ILUM.',
  'offline': 'sin conexión',
  'NEXT 7 DAYS': 'PRÓXIMOS 7 DÍAS',
  'Tomorrow': 'Mañana',
  '14-day forecasts': 'Pronósticos de 14 días',
  'My Locations': 'Mis ubicaciones',
  'ACTIVE': 'ACTIVA',
  'DETAILS': 'DETALLES',
  'Multiple locations': 'Varias ubicaciones',
  'Add location': 'Agregar ubicación',
  'Switch location': 'Cambiar ubicación',
  'Add a location': 'Agregar una ubicación',
  'Use my current location': 'Usar mi ubicación actual',
  'Search a city…': 'Buscar una ciudad…',
  'SUGGESTIONS': 'SUGERENCIAS',
  'No matches.': 'Sin resultados.',
  'Not now': 'Ahora no',
  'Open settings': 'Abrir configuración',
  'Updating weather…': 'Actualizando el clima…',
  'Weather unavailable': 'Datos del clima no disponibles',
  'UNITS & FORMAT': 'UNIDADES Y FORMATO',
  'Units': 'Unidades',
  'Time format': 'Formato de hora',
  'Example': 'Ejemplo',
  'NOTIFICATIONS': 'NOTIFICACIONES',
  'Daily summary': 'Resumen diario',
  'High-score day alert': 'Alerta de día con puntaje alto',
  'Period reminders': 'Recordatorios de períodos',
  'APPEARANCE & LANGUAGE': 'APARIENCIA E IDIOMA',
  'Theme': 'Tema',
  'Language': 'Idioma',
  'System': 'Sistema',
  'Dark': 'Oscuro',
  'Light': 'Claro',
  'Privacy policy': 'Política de privacidad',
  'About AnglerPulse': 'Acerca de AnglerPulse',
  'How is the score calculated?': '¿Cómo se calcula el puntaje?',
  'Moon phase': 'Fase lunar',
  'Dawn / dusk overlap': 'Coincidencia de amanecer y anochecer',
  'Pressure trend': 'Tendencia de presión',
  'Season': 'Temporada',
};

const _french = <String, String>{
  'Today': 'Aujourd’hui',
  'Forecast': 'Prévisions',
  'Locations': 'Lieux',
  'Settings': 'Réglages',
  'FISHING CONDITION': 'CONDITIONS DE PÊCHE',
  'ACTIVITY TIMELINE': 'CHRONOLOGIE D’ACTIVITÉ',
  'WEATHER': 'MÉTÉO',
  'SOLUNAR DATA': 'DONNÉES SOLUNAIRES',
  'WHY?': 'POURQUOI ?',
  'SCORE ': 'SCORE ',
  'Major window': 'Créneau majeur',
  'Minor window': 'Créneau mineur',
  'Daylight': 'Lumière du jour',
  'MAJOR': 'MAJEUR',
  'MINOR': 'MINEUR',
  'Hourly Activity': 'Activité horaire',
  'Solunar Periods': 'Périodes solunaires',
  'Hourly Weather': 'Météo horaire',
  'Set Reminder': 'Créer un rappel',
  'Major period': 'Période majeure',
  'Minor period': 'Période mineure',
  'Passed': 'Terminée',
  'TEMP': 'TEMP.',
  'WIND': 'VENT',
  'PRESSURE': 'PRESSION',
  'ILLUM': 'LUMIN.',
  'offline': 'hors ligne',
  'NEXT 7 DAYS': '7 PROCHAINS JOURS',
  'Tomorrow': 'Demain',
  '14-day forecasts': 'Prévisions sur 14 jours',
  'My Locations': 'Mes lieux',
  'ACTIVE': 'ACTIF',
  'DETAILS': 'DÉTAILS',
  'Multiple locations': 'Plusieurs lieux',
  'Add location': 'Ajouter un lieu',
  'Switch location': 'Changer de lieu',
  'Add a location': 'Ajouter un lieu',
  'Use my current location': 'Utiliser ma position actuelle',
  'Search a city…': 'Rechercher une ville…',
  'SUGGESTIONS': 'SUGGESTIONS',
  'No matches.': 'Aucun résultat.',
  'Not now': 'Pas maintenant',
  'Open settings': 'Ouvrir les réglages',
  'Updating weather…': 'Mise à jour de la météo…',
  'Weather unavailable': 'Données météo indisponibles',
  'UNITS & FORMAT': 'UNITÉS ET FORMAT',
  'Units': 'Unités',
  'Time format': 'Format de l’heure',
  'Example': 'Exemple',
  'NOTIFICATIONS': 'NOTIFICATIONS',
  'Daily summary': 'Résumé quotidien',
  'High-score day alert': 'Alerte de journée à score élevé',
  'Period reminders': 'Rappels de périodes',
  'APPEARANCE & LANGUAGE': 'APPARENCE ET LANGUE',
  'Theme': 'Thème',
  'Language': 'Langue',
  'System': 'Système',
  'Dark': 'Sombre',
  'Light': 'Clair',
  'Privacy policy': 'Politique de confidentialité',
  'About AnglerPulse': 'À propos d’AnglerPulse',
  'How is the score calculated?': 'Comment le score est-il calculé ?',
  'Moon phase': 'Phase lunaire',
  'Dawn / dusk overlap': 'Chevauchement entre aube et crépuscule',
  'Pressure trend': 'Tendance de la pression',
  'Season': 'Saison',
};

const _german = <String, String>{
  'Today': 'Heute',
  'Forecast': 'Vorhersage',
  'Locations': 'Orte',
  'Settings': 'Einstellungen',
  'FISHING CONDITION': 'ANGELBEDINGUNGEN',
  'ACTIVITY TIMELINE': 'AKTIVITÄTSZEITLEISTE',
  'WEATHER': 'WETTER',
  'SOLUNAR DATA': 'SOLUNARDATEN',
  'WHY?': 'WARUM?',
  'SCORE ': 'WERTUNG ',
  'Major window': 'Hauptfenster',
  'Minor window': 'Nebenfenster',
  'Daylight': 'Tageslicht',
  'MAJOR': 'HAUPT',
  'MINOR': 'NEBEN',
  'Hourly Activity': 'Stündliche Aktivität',
  'Solunar Periods': 'Solunarperioden',
  'Hourly Weather': 'Stündliches Wetter',
  'Set Reminder': 'Erinnerung setzen',
  'Major period': 'Hauptperiode',
  'Minor period': 'Nebenperiode',
  'Passed': 'Vorbei',
  'TEMP': 'TEMP.',
  'WIND': 'WIND',
  'PRESSURE': 'DRUCK',
  'ILLUM': 'BELEUCHT.',
  'offline': 'offline',
  'NEXT 7 DAYS': 'NÄCHSTE 7 TAGE',
  'Tomorrow': 'Morgen',
  '14-day forecasts': '14-Tage-Vorhersagen',
  'My Locations': 'Meine Orte',
  'ACTIVE': 'AKTIV',
  'DETAILS': 'DETAILS',
  'Multiple locations': 'Mehrere Orte',
  'Add location': 'Ort hinzufügen',
  'Switch location': 'Ort wechseln',
  'Add a location': 'Ort hinzufügen',
  'Use my current location': 'Meinen aktuellen Standort verwenden',
  'Search a city…': 'Stadt suchen…',
  'SUGGESTIONS': 'VORSCHLÄGE',
  'No matches.': 'Keine Treffer.',
  'Not now': 'Nicht jetzt',
  'Open settings': 'Einstellungen öffnen',
  'Updating weather…': 'Wetter wird aktualisiert…',
  'Weather unavailable': 'Wetterdaten nicht verfügbar',
  'UNITS & FORMAT': 'EINHEITEN UND FORMAT',
  'Units': 'Einheiten',
  'Time format': 'Zeitformat',
  'Example': 'Beispiel',
  'NOTIFICATIONS': 'BENACHRICHTIGUNGEN',
  'Daily summary': 'Tagesübersicht',
  'High-score day alert': 'Hinweis für Tage mit hoher Wertung',
  'Period reminders': 'Periodenerinnerungen',
  'APPEARANCE & LANGUAGE': 'DARSTELLUNG UND SPRACHE',
  'Theme': 'Design',
  'Language': 'Sprache',
  'System': 'System',
  'Dark': 'Dunkel',
  'Light': 'Hell',
  'Privacy policy': 'Datenschutzerklärung',
  'About AnglerPulse': 'Über AnglerPulse',
  'How is the score calculated?': 'Wie wird die Wertung berechnet?',
  'Moon phase': 'Mondphase',
  'Dawn / dusk overlap': 'Überlappung von Morgen- und Abenddämmerung',
  'Pressure trend': 'Luftdrucktrend',
  'Season': 'Jahreszeit',
};

const _swedish = <String, String>{
  'Today': 'I dag',
  'Forecast': 'Prognos',
  'Locations': 'Platser',
  'Settings': 'Inställningar',
  'FISHING CONDITION': 'FISKEFÖRHÅLLANDEN',
  'ACTIVITY TIMELINE': 'AKTIVITETSTIDSLINJE',
  'WEATHER': 'VÄDER',
  'SOLUNAR DATA': 'SOLUNARDATA',
  'WHY?': 'VARFÖR?',
  'SCORE ': 'POÄNG ',
  'Major window': 'Huvudfönster',
  'Minor window': 'Mindre fönster',
  'Daylight': 'Dagsljus',
  'MAJOR': 'HUVUD',
  'MINOR': 'MINDRE',
  'Hourly Activity': 'Aktivitet per timme',
  'Solunar Periods': 'Solunarperioder',
  'Hourly Weather': 'Väder per timme',
  'Set Reminder': 'Ställ in påminnelse',
  'Major period': 'Huvudperiod',
  'Minor period': 'Mindre period',
  'Passed': 'Passerad',
  'TEMP': 'TEMP.',
  'WIND': 'VIND',
  'PRESSURE': 'LUFTTRYCK',
  'ILLUM': 'BELYSN.',
  'offline': 'offline',
  'NEXT 7 DAYS': 'KOMMANDE 7 DAGAR',
  'Tomorrow': 'I morgon',
  '14-day forecasts': '14-dagarsprognoser',
  'My Locations': 'Mina platser',
  'ACTIVE': 'AKTIV',
  'DETAILS': 'DETALJER',
  'Multiple locations': 'Flera platser',
  'Add location': 'Lägg till plats',
  'Switch location': 'Byt plats',
  'Add a location': 'Lägg till en plats',
  'Use my current location': 'Använd min nuvarande plats',
  'Search a city…': 'Sök efter en stad…',
  'SUGGESTIONS': 'FÖRSLAG',
  'No matches.': 'Inga träffar.',
  'Not now': 'Inte nu',
  'Open settings': 'Öppna inställningar',
  'Updating weather…': 'Uppdaterar väder…',
  'Weather unavailable': 'Väderdata är inte tillgängliga',
  'UNITS & FORMAT': 'ENHETER OCH FORMAT',
  'Units': 'Enheter',
  'Time format': 'Tidsformat',
  'Example': 'Exempel',
  'NOTIFICATIONS': 'NOTISER',
  'Daily summary': 'Daglig sammanfattning',
  'High-score day alert': 'Varning för dag med hög poäng',
  'Period reminders': 'Periodpåminnelser',
  'APPEARANCE & LANGUAGE': 'UTSEENDE OCH SPRÅK',
  'Theme': 'Tema',
  'Language': 'Språk',
  'System': 'System',
  'Dark': 'Mörkt',
  'Light': 'Ljust',
  'Privacy policy': 'Integritetspolicy',
  'About AnglerPulse': 'Om AnglerPulse',
  'How is the score calculated?': 'Hur beräknas poängen?',
  'Moon phase': 'Månfas',
  'Dawn / dusk overlap': 'Överlappning mellan gryning och skymning',
  'Pressure trend': 'Lufttryckstrend',
  'Season': 'Säsong',
};

const _norwegian = <String, String>{
  'Today': 'I dag',
  'Forecast': 'Varsel',
  'Locations': 'Steder',
  'Settings': 'Innstillinger',
  'FISHING CONDITION': 'FISKEFORHOLD',
  'ACTIVITY TIMELINE': 'AKTIVITETSTIDSLINJE',
  'WEATHER': 'VÆR',
  'SOLUNAR DATA': 'SOLUNARDATA',
  'WHY?': 'HVORFOR?',
  'SCORE ': 'POENG ',
  'Major window': 'Hovedvindu',
  'Minor window': 'Mindre vindu',
  'Daylight': 'Dagslys',
  'MAJOR': 'HOVED',
  'MINOR': 'MINDRE',
  'Hourly Activity': 'Aktivitet per time',
  'Solunar Periods': 'Solunarperioder',
  'Hourly Weather': 'Vær per time',
  'Set Reminder': 'Sett påminnelse',
  'Major period': 'Hovedperiode',
  'Minor period': 'Mindre periode',
  'Passed': 'Passert',
  'TEMP': 'TEMP.',
  'WIND': 'VIND',
  'PRESSURE': 'TRYKK',
  'ILLUM': 'BELYSN.',
  'offline': 'frakoblet',
  'NEXT 7 DAYS': 'NESTE 7 DAGER',
  'Tomorrow': 'I morgen',
  '14-day forecasts': '14-dagersvarsler',
  'My Locations': 'Mine steder',
  'ACTIVE': 'AKTIV',
  'DETAILS': 'DETALJER',
  'Multiple locations': 'Flere steder',
  'Add location': 'Legg til sted',
  'Switch location': 'Bytt sted',
  'Add a location': 'Legg til et sted',
  'Use my current location': 'Bruk min nåværende posisjon',
  'Search a city…': 'Søk etter en by…',
  'SUGGESTIONS': 'FORSLAG',
  'No matches.': 'Ingen treff.',
  'Not now': 'Ikke nå',
  'Open settings': 'Åpne innstillinger',
  'Updating weather…': 'Oppdaterer vær…',
  'Weather unavailable': 'Værdata er ikke tilgjengelige',
  'UNITS & FORMAT': 'ENHETER OG FORMAT',
  'Units': 'Enheter',
  'Time format': 'Tidsformat',
  'Example': 'Eksempel',
  'NOTIFICATIONS': 'VARSLER',
  'Daily summary': 'Daglig oppsummering',
  'High-score day alert': 'Varsel om dag med høy poengsum',
  'Period reminders': 'Periodepåminnelser',
  'APPEARANCE & LANGUAGE': 'UTSEENDE OG SPRÅK',
  'Theme': 'Tema',
  'Language': 'Språk',
  'System': 'System',
  'Dark': 'Mørk',
  'Light': 'Lys',
  'Privacy policy': 'Personvernerklæring',
  'About AnglerPulse': 'Om AnglerPulse',
  'How is the score calculated?': 'Hvordan beregnes poengsummen?',
  'Moon phase': 'Månefase',
  'Dawn / dusk overlap': 'Overlapp mellom daggry og skumring',
  'Pressure trend': 'Trykktrend',
  'Season': 'Årstid',
};
